version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: opr_admin
      POSTGRES_PASSWORD: opr_admin
      POSTGRES_DB: opr
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
